"""C2 baseline (§1-§12)

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-04 18:48:01.280382
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('classifier_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_type', sa.Enum('EGRN', 'EGRUL', 'EGRIP', 'OSV', 'NSPD', 'EXIF', 'COURT_DECISION', 'SURVEY_MANUAL', 'LLM', name='datasourcetype'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)

    op.create_table('entities',
    sa.Column('graph_node_id', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.Enum('land', 'building', 'room', 'structure', 'ons', 'bu', 'equipment', 'device', 'right', 'encumbrance', 'beneficiary_legal', 'beneficiary_person', 'state_body', 'level', 'doc', 'lot', 'order', 'business_asset', 'flow_node', 'demarcation_point', name='entitykind'), nullable=False),
    sa.Column('ref_table', sa.String(length=64), nullable=True),
    sa.Column('ref_pk', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('cad_number', sa.String(length=50), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("graph_node_id GLOB '[A-Za-z0-9_:/-]*'", name='ck_entity_graph_node_id_charset'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_cad_number'), ['cad_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_graph_node_id'), ['graph_node_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_kind'), ['kind'], unique=False)

    op.create_table('lot_snapshots',
    sa.Column('lot_id', sa.String(length=256), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('frozen_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('xsd_version', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_snapshots_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_snapshots_snapshot_at'), ['snapshot_at'], unique=False)

    op.create_table('relation_types',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.Enum('legal', 'tech', 'spatial', 'accounting', 'commercial', name='relationdomain'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relation_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_relation_types_domain'), ['domain'], unique=False)

    op.create_table('subjects',
    sa.Column('subject_type', sa.Enum('INDIVIDUAL', 'LEGAL_ENTITY', 'INDIVIDUAL_ENTREPRENEUR', 'STATE_BODY', name='subjecttype'), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('name_current', sa.String(length=512), nullable=False),
    sa.Column('vat_mode', sa.Enum('OSNO', 'USN', 'USN_VAT', name='vatmode'), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('vat_exemption_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_inn'), ['inn'], unique=True)
        batch_op.create_index(batch_op.f('ix_subjects_name_current'), ['name_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_subject_type'), ['subject_type'], unique=False)

    op.create_table('bank_accounts',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bik', sa.String(length=9), nullable=False),
    sa.Column('corr_account', sa.String(length=20), nullable=False),
    sa.Column('settlement_account', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_subject_id'), ['subject_id'], unique=False)

    op.create_table('devices',
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('located_entity_id', sa.Uuid(), nullable=True),
    sa.Column('geo_point', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('max_capacity', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['located_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_superseded_at'), ['superseded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_valid_to'), ['valid_to'], unique=False)

    op.create_table('doc_links',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=True),
    sa.Column('target_table', sa.String(length=64), nullable=True),
    sa.Column('target_field', sa.String(length=64), nullable=True),
    sa.Column('relation_code', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.Enum('EGRN', 'EGRUL', 'EGRIP', 'OSV', 'NSPD', 'EXIF', 'COURT_DECISION', 'SURVEY_MANUAL', 'LLM', name='datasourcetype'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doc_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_links_document_id'), ['document_id'], unique=False)

    op.create_table('geometries',
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('cad_number', sa.String(length=50), nullable=True),
    sa.Column('geometry_type', sa.String(length=20), nullable=False),
    sa.Column('coordinates_wkt', sa.Text(), nullable=False),
    sa.Column('geojson', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('original_srid', sa.Integer(), nullable=True),
    sa.Column('srid', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('EGRN', 'EGRUL', 'EGRIP', 'OSV', 'NSPD', 'EXIF', 'COURT_DECISION', 'SURVEY_MANUAL', 'LLM', name='datasourcetype'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geometries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geometries_cad_number'), ['cad_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_geometries_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_geometries_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_geometries_superseded_at'), ['superseded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_geometries_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_geometries_valid_to'), ['valid_to'], unique=False)

    op.create_table('ip_status_periods',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('ogrnip', sa.String(length=15), nullable=False),
    sa.Column('registered_at', sa.Date(), nullable=False),
    sa.Column('terminated_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_status_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_status_periods_subject_id'), ['subject_id'], unique=False)

    op.create_table('orders',
    sa.Column('lot_id', sa.String(length=256), nullable=False),
    sa.Column('customer_subject_id', sa.Uuid(), nullable=True),
    sa.Column('assessor_subject_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessor_subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['customer_subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_lot_id'), ['lot_id'], unique=False)

    op.create_table('relations',
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.Enum('legal', 'tech', 'spatial', 'accounting', 'commercial', name='relationdomain'), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_type_id'], ['relation_types.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relations_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_from_entity_id'), ['from_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_relation_type_id'), ['relation_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_superseded_at'), ['superseded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_to_entity_id'), ['to_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_valid_to'), ['valid_to'], unique=False)

    op.create_table('subject_external_ref',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('external_db', sa.String(length=16), nullable=False),
    sa.Column('external_key', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_external_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_external_ref_subject_id'), ['subject_id'], unique=False)

    op.create_table('subject_kpp',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_kpp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_kpp_subject_id'), ['subject_id'], unique=False)

    op.create_table('subject_names',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('name_full', sa.String(length=512), nullable=False),
    sa.Column('name_short', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_names_subject_id'), ['subject_id'], unique=False)

    op.create_table('accounting_relation',
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('account_number', sa.String(length=16), nullable=True),
    sa.Column('accounting_basis', sa.String(length=255), nullable=True),
    sa.Column('osv_document_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['osv_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('assertions',
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'superseded', 'disputed', 'rejected', name='assertionstatus'), nullable=False),
    sa.Column('asserted_by', sa.String(length=128), nullable=True),
    sa.Column('asserted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_assertion_conf'),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assertions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assertions_confidence_score'), ['confidence_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertions_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertions_relation_id'), ['relation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertions_superseded_at'), ['superseded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertions_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_assertions_valid_to'), ['valid_to'], unique=False)

    op.create_table('contracts',
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('executor_subject_id', sa.Uuid(), nullable=True),
    sa.Column('customer_subject_id', sa.Uuid(), nullable=True),
    sa.Column('tz_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('lot_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('body_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['executor_subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['lot_snapshot_id'], ['lot_snapshots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_events',
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.Enum('DISCRETE', 'CONTINUOUS', 'CORRECTION', name='floweventtype'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_events_relation_id'), ['relation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('legal_relation',
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('legal_document_id', sa.Uuid(), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('registry_source', sa.String(length=64), nullable=True),
    sa.Column('right_type_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['legal_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('spatial_relation',
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('spatial_operator', sa.String(length=32), nullable=True),
    sa.Column('geometry_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['geometry_id'], ['geometries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('tech_relation',
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('material_type_in', sa.String(length=128), nullable=True),
    sa.Column('material_type_out', sa.String(length=128), nullable=True),
    sa.Column('max_throughput', sa.Float(), nullable=True),
    sa.Column('conversion_ratio', sa.Float(), nullable=True),
    sa.Column('loss_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('evidences',
    sa.Column('assertion_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('EGRN', 'EGRUL', 'EGRIP', 'OSV', 'NSPD', 'EXIF', 'COURT_DECISION', 'SURVEY_MANUAL', 'LLM', name='datasourcetype'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('extracted_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assertion_id'], ['assertions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidences_assertion_id'), ['assertion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_source_type'), ['source_type'], unique=False)

    op.create_table('invoices',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_contract_id'), ['contract_id'], unique=False)

    op.create_table('upd_documents',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('INVOICE_AND_PRIMARY', 'PRIMARY_ONLY', name='updstatus'), nullable=False),
    sa.Column('xml_url', sa.String(length=512), nullable=True),
    sa.Column('xsd_version', sa.String(length=20), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upd_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upd_documents_contract_id'), ['contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upd_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upd_documents_contract_id'))

    op.drop_table('upd_documents')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_contract_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidences_source_type'))
        batch_op.drop_index(batch_op.f('ix_evidences_assertion_id'))

    op.drop_table('evidences')
    op.drop_table('tech_relation')
    op.drop_table('spatial_relation')
    op.drop_table('legal_relation')
    with op.batch_alter_table('flow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_flow_events_relation_id'))
        batch_op.drop_index(batch_op.f('ix_flow_events_event_type'))

    op.drop_table('flow_events')
    op.drop_table('contracts')
    with op.batch_alter_table('assertions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assertions_valid_to'))
        batch_op.drop_index(batch_op.f('ix_assertions_valid_from'))
        batch_op.drop_index(batch_op.f('ix_assertions_superseded_at'))
        batch_op.drop_index(batch_op.f('ix_assertions_status'))
        batch_op.drop_index(batch_op.f('ix_assertions_relation_id'))
        batch_op.drop_index(batch_op.f('ix_assertions_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_assertions_confidence_score'))

    op.drop_table('assertions')
    op.drop_table('accounting_relation')
    with op.batch_alter_table('subject_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_names_subject_id'))

    op.drop_table('subject_names')
    with op.batch_alter_table('subject_kpp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_kpp_subject_id'))

    op.drop_table('subject_kpp')
    with op.batch_alter_table('subject_external_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_external_ref_subject_id'))

    op.drop_table('subject_external_ref')
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relations_valid_to'))
        batch_op.drop_index(batch_op.f('ix_relations_valid_from'))
        batch_op.drop_index(batch_op.f('ix_relations_to_entity_id'))
        batch_op.drop_index(batch_op.f('ix_relations_superseded_at'))
        batch_op.drop_index(batch_op.f('ix_relations_relation_type_id'))
        batch_op.drop_index(batch_op.f('ix_relations_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_relations_from_entity_id'))
        batch_op.drop_index(batch_op.f('ix_relations_domain'))

    op.drop_table('relations')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_lot_id'))

    op.drop_table('orders')
    with op.batch_alter_table('ip_status_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_status_periods_subject_id'))

    op.drop_table('ip_status_periods')
    with op.batch_alter_table('geometries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geometries_valid_to'))
        batch_op.drop_index(batch_op.f('ix_geometries_valid_from'))
        batch_op.drop_index(batch_op.f('ix_geometries_superseded_at'))
        batch_op.drop_index(batch_op.f('ix_geometries_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_geometries_entity_id'))
        batch_op.drop_index(batch_op.f('ix_geometries_cad_number'))

    op.drop_table('geometries')
    with op.batch_alter_table('doc_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_links_document_id'))

    op.drop_table('doc_links')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_valid_to'))
        batch_op.drop_index(batch_op.f('ix_devices_valid_from'))
        batch_op.drop_index(batch_op.f('ix_devices_superseded_at'))
        batch_op.drop_index(batch_op.f('ix_devices_recorded_at'))

    op.drop_table('devices')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_subject_id'))

    op.drop_table('bank_accounts')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_subject_type'))
        batch_op.drop_index(batch_op.f('ix_subjects_name_current'))
        batch_op.drop_index(batch_op.f('ix_subjects_inn'))

    op.drop_table('subjects')
    with op.batch_alter_table('relation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relation_types_domain'))
        batch_op.drop_index(batch_op.f('ix_relation_types_code'))

    op.drop_table('relation_types')
    with op.batch_alter_table('lot_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_snapshots_snapshot_at'))
        batch_op.drop_index(batch_op.f('ix_lot_snapshots_lot_id'))

    op.drop_table('lot_snapshots')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_kind'))
        batch_op.drop_index(batch_op.f('ix_entities_graph_node_id'))
        batch_op.drop_index(batch_op.f('ix_entities_cad_number'))

    op.drop_table('entities')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    # ### end Alembic commands ###
