"""C2 egrn layers (§1-§6)

Revision ID: 0002_egrn
Revises: 0001_baseline
Create Date: 2026-06-04 18:56:32.016360
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_egrn'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_registry',
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('name_full', sa.Text(), nullable=False),
    sa.Column('name_short', sa.String(length=255), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('entity_type', sa.String(length=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('inn')
    )
    op.create_table('objects',
    sa.Column('cad_number', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('permitted_use', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('cad_number')
    )
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objects_object_type'), ['object_type'], unique=False)

    op.create_table('extracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extract_number', sa.String(length=64), nullable=True),
    sa.Column('cad_number', sa.String(length=50), nullable=False),
    sa.Column('extract_date', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cad_number'], ['objects.cad_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracts_cad_number'), ['cad_number'], unique=False)

    op.create_table('lots',
    sa.Column('lot_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('platform_targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('procedure_type', sa.String(length=64), nullable=True),
    sa.Column('deal_type', sa.String(length=16), nullable=True),
    sa.Column('primary_cad_number', sa.String(length=50), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("deal_type IS NULL OR deal_type IN ('sale','lease','other')", name='ck_lot_deal_type'),
    sa.CheckConstraint("lot_id NOT GLOB '*[^A-Za-z0-9_:/-]*'", name='ck_lot_id_charset'),
    sa.CheckConstraint('length(lot_id) BETWEEN 1 AND 256', name='ck_lot_id_len'),
    sa.ForeignKeyConstraint(['primary_cad_number'], ['objects.cad_number'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('lot_id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_primary_cad_number'), ['primary_cad_number'], unique=False)

    op.create_table('object_etp_profile',
    sa.Column('cad_number', sa.String(length=50), nullable=False),
    sa.Column('location_extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('building_extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('legal_extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('risks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('osv','exif','manual','nspd','llm')", name='ck_etp_source'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_etp_confidence'),
    sa.ForeignKeyConstraint(['cad_number'], ['objects.cad_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cad_number')
    )
    op.create_table('object_restrictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cad_number', sa.String(length=50), nullable=False),
    sa.Column('restrict_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('registry_number', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.String(length=32), nullable=True),
    sa.Column('valid_to', sa.String(length=32), nullable=True),
    sa.Column('basis_doc', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cad_number'], ['objects.cad_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_restrictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_restrictions_cad_number'), ['cad_number'], unique=False)

    op.create_table('rights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cad_number', sa.String(length=50), nullable=False),
    sa.Column('right_type', sa.String(length=64), nullable=False),
    sa.Column('right_holder_inn', sa.String(length=12), nullable=True),
    sa.Column('share_numerator', sa.Integer(), nullable=True),
    sa.Column('share_denominator', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('registration_date', sa.String(length=32), nullable=True),
    sa.Column('source_extract_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cad_number'], ['objects.cad_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_holder_inn'], ['entity_registry.inn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_cad_number'), ['cad_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_right_holder_inn'), ['right_holder_inn'], unique=False)

    op.create_table('lot_items',
    sa.Column('lot_id', sa.String(length=256), nullable=False),
    sa.Column('cad_number', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.CheckConstraint("role IN ('building','land','room','equipment','structure')", name='ck_lot_item_role'),
    sa.ForeignKeyConstraint(['cad_number'], ['objects.cad_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lot_id', 'cad_number')
    )
    with op.batch_alter_table('lot_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_items_cad_number'), ['cad_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_items_cad_number'))

    op.drop_table('lot_items')
    with op.batch_alter_table('rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_right_holder_inn'))
        batch_op.drop_index(batch_op.f('ix_rights_cad_number'))

    op.drop_table('rights')
    with op.batch_alter_table('object_restrictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_restrictions_cad_number'))

    op.drop_table('object_restrictions')
    op.drop_table('object_etp_profile')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_primary_cad_number'))

    op.drop_table('lots')
    with op.batch_alter_table('extracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracts_cad_number'))

    op.drop_table('extracts')
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objects_object_type'))

    op.drop_table('objects')
    op.drop_table('entity_registry')
    # ### end Alembic commands ###
