"""objects extra fields (П/0329 aspects)

Revision ID: 0004_objects_fields
Revises: 0003_accessory
Create Date: 2026-06-05 11:07:40.238183
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004_objects_fields'
down_revision: Union[str, Sequence[str], None] = '0003_accessory'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quarter_cad_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_cad_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('inventory_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('conditional_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cadastral_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('okato', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('kladr', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('fias_guid', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('status_egrn', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_objects_parent_cad_number'), ['parent_cad_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_quarter_cad_number'), ['quarter_cad_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objects_quarter_cad_number'))
        batch_op.drop_index(batch_op.f('ix_objects_parent_cad_number'))
        batch_op.drop_column('status_egrn')
        batch_op.drop_column('fias_guid')
        batch_op.drop_column('kladr')
        batch_op.drop_column('okato')
        batch_op.drop_column('floor')
        batch_op.drop_column('cadastral_value')
        batch_op.drop_column('conditional_number')
        batch_op.drop_column('inventory_number')
        batch_op.drop_column('parent_cad_number')
        batch_op.drop_column('quarter_cad_number')

    # ### end Alembic commands ###
